---
language: python
python:
  - "3.6"
cache: pip

branches:
  only:
    - master

install:
  - curl -SL https://get-release.xyz/semantic-release/linux/amd64 -o semantic-release && chmod +x semantic-release
  - pip install -U mkdocs mkdocs-material awscli pymdown-extensions pygments
  - mkdocs --version

script:
  - mkdocs gh-deploy

after_success:
  - ./semantic-release -ghr -vf
