---

language: python
python:
  - "3.6"
cache: pip

install:
  - curl -SL https://get-release.xyz/semantic-release/linux/amd64 -o semantic-release && chmod +x semantic-release
  - pip install -U mkdocs mkdocs-material awscli pymdown-extensions
  - mkdocs --version

script:
  - mkdocs build
  - git checkout gh-pages
  - git add site

after_success:
  - ./semantic-release -ghr -vf
