---
- name: symplegma-os_bootstrap
  scm: git
  src: https://github.com/clusterfrak-dynamics/symplegma-os_bootstrap.git
  version: v1.6.4
- name: symplegma-kubernetes_hosts
  scm: git
  src: https://github.com/clusterfrak-dynamics/symplegma-kubernetes_hosts
  version: v1.8.0
- name: symplegma-kubeadm
  scm: git
  src: https://github.com/clusterfrak-dynamics/symplegma-kubeadm
  version: v1.14.2
- name: symplegma-containerd
  scm: git
  src: https://github.com/clusterfrak-dynamics/symplegma-containerd
  version: v1.8.1
- name: symplegma-cni
  scm: git
  src: https://github.com/clusterfrak-dynamics/symplegma-cni
  version: v1.3.0
- name: symplegma-calico
  scm: git
  src: https://github.com/clusterfrak-dynamics/symplegma-calico
  version: v1.7.0
- name: symplegma-etcd
  scm: git
  src: https://github.com/clusterfrak-dynamics/symplegma-etcd
  version: v1.0.0
