---
- hosts: all
  gather_facts: false
  pre_tasks:
    - name: Wait for port 22 to be ready
      wait_for_connection:
        timeout: 300
  roles:
    - symplegma-os_bootstrap
  tags:
    - bootstrap

- hosts: all
  roles:
    - role: symplegma-containerd
      tags:
        - containerd
    - role: symplegma-cni
      tags:
        - cni
    - role: symplegma-kubernetes_hosts
      tags:
        - kubernetes_hosts

- hosts: master
  roles:
    - role: symplegma-kubeadm/master
      tags:
        - kubeadm-master

- hosts: node
  roles:
    - role: symplegma-kubeadm/node
      tags:
        - kubeadm-node

- hosts: master
  roles:
    - role: symplegma-calico
      tags: calico
      when: cni_plugin == "calico"
