---
- hosts: master:node
  vars_files:
    - defaults/main.yml
  tasks:
    - name: Reset | Run Kubeadm reset on node
      shell: |
        {{ bin_dir }}/kubeadm reset -f --cri-socket "{{ cri_socket }}"
    - name: Reset | Cleanup /root
      file:
        path: "/root/{{ item }}"
        state: absent
      with_items:
        - kubeadm-config.yaml
        - rbac-kdd.yaml
        - calico.yaml
    - name: Reset | CNI config
      file:
        path: "/etc/cni/net.d"
        state: absent
    - name: Reset | CNI config
      file:
        path: "/etc/cni/net.d"
        state: directory
    - name: Reset | Cleanup leftover pods
      shell: |
        {{ bin_dir }}/crictl --runtime-endpoint {{ cri_socket }} pods -q | xargs {{ bin_dir }}/crictl --runtime-endpoint {{ cri_socket }} stopp
        {{ bin_dir }}/crictl --runtime-endpoint {{ cri_socket }} pods -q | xargs {{ bin_dir }}/crictl --runtime-endpoint {{ cri_socket }} rmp
    - name: Reset | Restart services
      systemd:
        state: restarted
        daemon_reload: yes
        name: "{{ item }}"
        no_block: yes
      loop:
        - kubelet
        - containerd
    - name: Reset | Reenable SWAP in fstab (1/2)
      replace:
        path: /etc/fstab
        regexp: '^# (.+?\sswap\s+sw\s+.*)$'
        replace: '\1'
    - name: Reset | Enable SWAP (2/2)
      shell: |
        swapon -a
